### ISSUE TITLE
NRPD 2.0.1 does not work with SSL

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nrdp#44] opened 2019-07-31 19:18 UTC
It seems like NRPD 2.0.1 (and possibly 2.0.2) does not work with the following option set in config.inc.php:

`$cfg["require_https"] = true;`

The issue was reported on the Nagios Support forum here:

https://support.nagios.com/forum/viewtopic.php?t=54905#288621

I was able to recreate it in Nagios XI 5.6.5 with NRPD 2.0.1. Accessing NRDP by going to:

`https://<ip address>/nrdp/`

generates the "HTTPS REQUIRED" error in the GUI.

Additional info:
I was hoping for find some clues in the logs, so I enabled debugging by setting:

```
$cfg["debug"] = true;
$cfg["debug_log"] = "/usr/local/nrdp/server/debug.log";
```
in config.inc.php, however the debug.log didn't get created. Am I missing something?

**Comment by Bangaio65** [comment] 2019-08-16 01:42
nrdp 2.0.2
Setting it to `true`, I can send requests via http, but https gives HTTPS REQUIRED. Should be the other way, no?

**Comment by ericloyd** [comment] 2019-08-22 19:58
NRDP seems to have taken quite the hit lately in bugs.  Is there some sort of outbreak?

**Comment by jomann09** [comment] 2019-08-22 20:07
This should have been fixed in 2.0.2 indirectly by reverting a change that was made in NRDP 2.0 but will double check this

**Comment by SheffSix** [comment] 2020-01-06 13:29
Sorry to bump. I just installed a fresh 2.0.2 instance (cloned from github) and I am getting seeing this on my install. Can you confirm if it did get patched or if there's a workaround please?

**Comment by jomann09** [comment] 2020-01-06 15:16
Do you have any output in the apache error log? This was fixed because there was a missing function that caused it to not process correctly. It should be working fine in the latest (just tested it with 2.0.2).

**Comment by SheffSix** [comment] 2020-01-06 16:47
Nothing at all in the error log

**Comment by SheffSix** [comment] 2020-01-06 17:12
I enabled debug logging and am seeing:

`[Mon, 06 Jan 2020 17:09:57 +0000] check_auth()
[Mon, 06 Jan 2020 17:09:57 +0000]  * require_https either not set or non-false (is required)
[Mon, 06 Jan 2020 17:09:57 +0000]  * no https usage, denying auth
[Mon, 06 Jan 2020 17:09:57 +0000] handle_api_error(msg=HTTPS REQUIRED)
`

I have double and triple-checked my browser is connecting by https and has a valid certificate.

**Comment by jomann09** [comment] 2020-01-06 17:18
Did you set the $cfg option in the server config.inc.php when you upgraded to 2.0.2? The option should be located in `/urs/local/nrdp/server/config.inc.php` must have `$cfg["require_https"] = true;` for HTTPs to work. By default it is disabled.

**Comment by jomann09** [comment] 2020-01-06 17:21
Actually it looks like you're making it in there properly, are you sending your requests via HTTPS? We don't convert HTTP -> HTTPS when you set that value.

**Comment by SheffSix** [comment] 2020-01-06 17:29
This isn't an upgrade. It's a first-time install. I pulled the source from Git with git clone ...

Apache is configured for SSL, the NDRP virtual directory has the SSLRequireSSL option. Any traffic on 80 is redirected to 443 by the default apache config.

I'm definitely calling from https:// on the browser

**Comment by jomann09** [comment] 2020-01-06 17:31
Hmm okay so the issue is, it seems, that the empty() is doing `!empty()` on line https://github.com/NagiosEnterprises/nrdp/blob/master/server/includes/utils.inc.php#L454 you can edit the file manually in `/usr/local/nrdp/server/includes/utils.inc.php`. That was a change that occured in 2 which is likely the issue. It's checking if the require_https == true, and if it is, then HTTPS should be set to a non-empty value. Meaning if it is empty, it should error.

**Comment by SheffSix** [comment] 2020-01-06 17:35
So what do I change? (Sorry!)

**Comment by SheffSix** [comment] 2020-01-06 17:39
Ah, change `!empty()` to `empty()` ? that what I've done and I'm in now.

**Comment by jomann09** [comment] 2020-01-06 17:40
Yeah that's all that needed to change. I actually just pushed the fix into master, too but if you got the change set then you're good to go. Sorry about not understanding earlier!

**Comment by SheffSix** [comment] 2020-01-06 17:41
Awesome, thanks for your help.

**Comment by jomann09** [comment] 2020-01-06 17:43
No problem, closing this with the fix.

**Closed by jomann09** 2020-01-06 17:43 UTC
Labels: Bug
