### ISSUE TITLE
http://<nagios ip>/nrdp not working

### ISSUE THREAD

**Issue by Skillz0r** [NagiosEnterprises/nrdp#11] opened 2016-07-28 13:25 UTC
Hey guys. I've been using Nagios for almost 2 years now. 
I've had all our configuration as active checks. Now, we need some passive checks since we can't reach some remote machines.
After following the steps, and installing nrdp on my ubuntu 15, I saw that my apache is on apache2 folder, and not on httpd. I did the NRDP configuration on my apache2 conf-available folder.
After restarting apache, I can't reach http://<nagios ip>/nrdp. it just says "The requested URL /nrdp was not found on this server."
Do I have to do anything diferente as this being apache2? httpd folder dsn't exist on my machine. 
Ty in advance

**Comment by cheng0214** [comment] 2016-10-04 09:49
You can put the configuration on conf-enabled folder,try it!

**Comment by rcuart** [comment] 2016-11-15 13:39
Hey!
I've had the same problem with NRDP installation on Ubuntu Server 16.04.
The tutorial says something about httpd and this folder doesn't exist so I used the /etc/apache2/conf-available folder and then i executed the "a2enconf nrdp.conf" command to enable it.
The problem is that after finishing the installation and trying "http://<myipaddress>/nrdp" it returned a 500 server error and consequently a blank page.
¿Does anyone know why?
I added the line "Require all granted" to the nrdp.conf file because the first time i tried it returned a "Not permission on this folder".

Thanks in advance!

**Comment by jomann09** [comment] 2016-12-01 00:54
Making this as a question and closing it. They are correct, you will need to place it in `conf-enabled` or use the  `a2enmod` command if available on your OS - which really just moves it from the available to enabled directory for you. Restart and you're done!

**Closed by jomann09** 2016-12-01 00:54 UTC
Labels: question
